export default {
  language: "en",
  dndInactiveStatus: [
    "Yello. You have allowed your number to receive all types of messages communicated by MTN. Thank you.",
    "Yello. You have blocked your number from receiving all non mandatory communication messages from MTN. Thank you.",
  ],
  broadcast: [{ name: "Merry ChristMas!!!" }],
  actions: [
    { code: "completed", name: "Complete" },
    { code: "rejected", name: "Reject" },
    { code: "canceled", name: "Cancel" },
    { code: "held", name: "Hold" },
  ],
  outlets: [
    {
      code: "mtng",
      name: "Ghana",
      defaultLat: "8.181321",
      defaultLong: "-1.308169",
      outlets: [
        {
          name: "MTN Kejetia Service Center",
          position: [6.70123, -1.62394],
          address: "Kejetia Market, Kumasi Municipal Assembly",
        },
        {
          name: "MTN Mampong Service Center",
          position: [7.054862, -1.4023306],
          address: "Abrukutuase, Mampong Municipal Assembly",
        },
      ],
    },
    {
      code: "mtnug",
      name: "Uganda",
      defaultLat: "1.381705",
      defaultLong: "32.296330",
      outlets: [
        {
          name: "Business Solutions Centre",
          position: [0.318499, 32.588672],
          address: "Crested Towers Building, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Mbarara Service Centre",
          position: [-0.510888, 30.6674],
          address:
            "Plot 5 High Street Mbarara, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Kyaggwe Service Centre",
          position: [0.31704, 32.571452],
          address:
            "Mukwano Mall, Kyaggwe Road, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Lugogo Mall Service Centre",
          position: [0.326754, 32.606413],
          address:
            "Shoprite Mall Lugogo, Jinja road, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Jinja Service Centre",
          position: [0.463259, 33.201863],
          address:
            "Plot 54, Lubas Road, Casino Building P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Shoprite Clock tower Service Centre",
          position: [0.311114, 32.576917],
          address:
            "Shoprite Mall, Ben Kiwanuka, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Kampala Road Service Centre",
          position: [0.313565, 32.580877],
          address: "Plot 28, Kampala Road, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Forest Mall Service Centre",
          position: [0.356975, 32.580928],
          address: "Forest Mall Ground Floor, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Mobile Service Centre",
          position: [0.358692, 32.582645],
          address: "P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Mbale Service Centre",
          position: [1.126355, 34.178605],
          address:
            "Plot 41, Republic Street, Mbale Town, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Fortportal Service Centre",
          position: [0.323713, 32.578118],
          address:
            "Baguma Crescent Building, Lugard Road, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Gulu Service Centre",
          position: [2.940967, 32.292578],
          address: "Plot 15 Nehru Road, Gulu, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Acacia Service Centre",
          position: [0.338746, 32.586752],
          address: "Acacia Mall, First Floor, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Village Mall Service Centre",
          position: [0.320436, 32.617535],
          address:
            "Village Mall Bugolobi 1st Floor, P.O. Box 24624, Kampala, Uganda",
        },
        {
          name: "Victoria Mall Service Centre",
          position: [0.360535, 32.581358],
          address:
            "Victoria mall Entebbe Ground Floor, P.O. Box 24624, Kampala, Uganda​",
        },
        {
          name: "Arua Service Centre",
          position: [3.158544, 30.919617],
          address:
            "Plot 47 Adumi Road Orasea Complex, Arua town, P.O. Box 24624, Kampala, Uganda",
        },
      ],
    },
  ],
  barUnBarStatus: [
    { code: "0", name: "barred" },
    { code: "1", name: "unBarred" },
  ],
  DonarServiceProvider: [
    { code: "AIRTEL", name: "Airtel Telecommunication" },
    { code: "VODAFONE", name: "Vodafone idea" },
    { code: "JIO", name: "JIO Telecom" },
  ],
  priority: [
    { code: "High", name: "High" },
    { code: "Low", name: "Low" },
    { code: "Medium", name: "Medium" },
    { code: "Critical", name: "Critical" },
  ],
  accountType: [
    { code: "Other", name: "Others", default: true },
    { code: "M2M", name: "M2M" },
  ],
  activatedVia: [
    { code: "WS", name: "White SIM", default: true },
    { code: "SP", name: "Starter Pack" },
    { code: "MNP", name: "Port In" },
  ],
  gprsSetting: [
    { code: "APN :web.gprs.mtnnigeria.net", name: "mtnweb" },
    { code: "APN :wap.gprs.mtnnigeria.net", name: "mtnwap" },
    { code: "wap.gprs.mtnnigeria.net", name: "manualSetting" },
  ],
  status: [
    { code: "softSuspended", name: "softSuspended" },
    { code: "draft", name: "draft" },
    { code: "captured", name: "captured" },
    { code: "created", name: "created" },
    { code: "active", name: "active" },
    { code: "inactive", name: "inactive" },
    { code: "acknowledged", name: "acknowledged" },
    { code: "partial", name: "partial" },
    { code: "cancelled", name: "cancelled" },
    { code: "held", name: "held" },
    { code: "failed", name: "failed" },
    { code: "inProgress", name: "inProgress" },
    { code: "rejected", name: "rejected" },
    { code: "pending", name: "pending" },
    { code: "pendingActive", name: "pendingActive" },
    { code: "pendingTerminate", name: "pendingTerminate" },
    { code: "assessingCancellation", name: "assessingCancellation" },
    { code: "uploaded", name: "uploaded" },
    { code: "resolved", name: "resolved" },
    { code: "completed", name: "completed" },
    { code: "fulfilled", name: "fulfilled" },
    { code: "suspended", name: "suspended" },
    { code: "terminated", name: "terminated" },
    { code: "aborted", name: "aborted" },
    { code: "received", name: "received" },
    { code: "verified", name: "verified" },
    { code: "validated", name: "validated" },
    { code: "initialized", name: "initialized" },
    { code: "deceased", name: "deceased" },
    { code: "closed", name: "closed" },
  ],
  preferredLanguage: [
    { code: "en", name: "English", default: true },
    { code: "fa", name: "Persian" },
    { code: "sp", name: "Spanish" },
  ],
  paymentMethod: [
    { code: "1", name: "Cash", type: "Cash", visible: true },
    { code: "2", name: "Cheque", type: "Cheque", visible: true },
    { code: "3", name: "Credit Card", type: "CreditCard", visible: true },
    { code: "4", name: "Debit Card", type: "DebitCard", visible: true },
    {
      code: "5",
      name: "Third Party Loyalty Voucher",
      type: "ThirdPartyLoyaltyVoucher",
      visible: false,
    },
    {
      code: "6",
      name: "Loyalty Voucher",
      type: "Loyalty Voucher",
      visible: false,
    },
    {
      code: "7",
      name: "Government Vouchers",
      type: "GovernmentVouchers",
      visible: false,
    },
    { code: "8", name: "Multiple Pay Mode", type: "BankFile", visible: false },
    { code: "9", name: "Credit", type: "Credit", visible: false },
    {
      code: "10",
      name: "Exchange Vouchers",
      type: "ExchangeVouchers",
      visible: false,
    },
    {
      code: "11",
      name: "Bank In Cheque",
      type: "BankInCheque",
      visible: false,
    },
    { code: "12", name: "Bank In Cash", type: "BankInCash", visible: false },
    { code: "30", name: "Mobile Money", type: "MoMoWallet", visible: true },
  ],
  country: [
    {
      code: "GH",
      name: "Ghana",
      default: true,
      province: [
        {
          code: "GHP1",
          name: "Greater Accra",
          city: [
            { code: "Accra", name: "Accra" },
            { code: "Tema", name: "Tema" },
          ],
        },
        {
          code: "GHP2",
          name: "Ashanti",
          city: [
            { code: "Kumasi", name: "Kumasi" },
            { code: "Ejura", name: "Ejura" },
          ],
        },
        {
          code: "GHP3",
          name: "Brong Ahafo",
          city: [
            { code: "Atebubu", name: "Atebubu" },
            { code: "Berekum", name: "Berekum" },
          ],
        },
        {
          code: "GHP4",
          name: "Central",
          city: [
            { code: "CapeCoast", name: "Cape Coast" },
            { code: "Tamale", name: "Tamale" },
          ],
        },
      ],
    },
    {
      code: "MU",
      name: "Mauritius",
      province: [
        {
          code: "S1",
          name: "port Louis",
          city: [
            { code: "PORTLOUIS", name: "Port Louis" },
            { code: "ABERCROMBIE", name: "Abercrombie" },
            { code: "ARSENAL", name: "Arsenal" },
            { code: "CASSIS", name: "Cassis" },
            { code: "COINBOXMTSLTD", name: "Coinbox Mts Ltd" },
            { code: "LATOURKOENIG", name: "La Tour Koenig" },
            { code: "M.C.B.PORTLOUIS", name: "M.C.B.  Port Louis" },
            { code: "MAURITIUSTELECOM", name: "Mauritius Telecom" },
            { code: "MLA", name: "Mla" },
            { code: "MONLOISIRDESJARD", name: "Mon Loisir Desjard" },
            { code: "PAILLES", name: "Pailles" },
            { code: "PLAINELAUZUN", name: "Plaine Lauzun" },
            { code: "POINTEAUXSABLES", name: "Pointe Aux Sables" },
            { code: "POLICEPAYOFFICE", name: "Police Pay Office" },
            { code: "RICHETERRE", name: "Riche Terre" },
            { code: "ROCHEBOIS", name: "Roche Bois" },
            { code: "STECROIX", name: "Ste Croix" },
            { code: "TERREROUGE", name: "Terre Rouge" },
            { code: "VALLEEDESPRETRES", name: "Vallee Des Pretres" },
          ],
        },
      ],
    },
    {
      code: "KW",
      name: "KUWAIT",
      province: [
        {
          code: "KW1",
          name: "Ahmadi",
          city: [
            { code: "Abu Halifa", name: "Abu Halifa" },
            { code: "Abdullah Port", name: "Abdullah Port" },
            { code: "Ahmadi", name: "Ahmadi" },
            { code: "Ali As-Salim", name: "Ali As-Salim" },
            { code: "Aqila", name: "Aqila" },
            { code: "Bar Al Ahmadi", name: "Bar Al Ahmadi" },
            { code: "Bneidar", name: "Bneidar" },
            { code: "Dhaher", name: "Dhaher" },
            { code: "Fahaheel", name: "Fahaheel" },
            { code: "Fahad Al-Ahmad", name: "Fahad Al-Ahmad" },
            { code: "Hadiya", name: "Hadiya" },
            { code: "Jaber Al-Ali", name: "Jaber Al-Ali" },
            { code: "Jawaher Al Wafra", name: "Jawaher Al Wafra" },
            { code: "Jileia", name: "Jileia" },
            { code: "Khairan", name: "Khairan" },
            { code: "Mahbula", name: "Mahbula" },
            { code: "Mangaf", name: "Mangaf" },
            { code: "Miqwa", name: "Miqwa" },
            { code: "New Khairan City", name: "New Khairan City" },
            { code: "New Wafra", name: "New Wafra" },
            { code: "Nuwaiseeb", name: "Nuwaiseeb" },
            { code: "Riqqa", name: "Riqqa" },
            { code: "Sabah Al-Ahmad City", name: "Sabah Al-Ahmad City" },
            {
              code: "Sabah Al-Ahmad Nautical City",
              name: "Sabah Al-Ahmad Nautical City",
            },
            { code: "Sabahiya", name: "Sabahiya" },
            {
              code: "ShuaibaA (North & South)",
              name: "ShuaibaA (North & South)",
            },
            { code: "South Sabahiya", name: "South Sabahiya" },
            { code: "Wafra", name: "Wafra" },
            { code: "Zoor", name: "Zoor" },
            { code: "Zuhar", name: "Zuhar" },
          ],
        },
        {
          code: "KW2",
          name: "Farwaniya",
          city: [
            { code: "Abdullah Al-Mubarak", name: "Abdullah Al-Mubarak" },
            { code: "Airport District", name: "Airport District" },
            { code: "Andalous", name: "Andalous" },
            { code: "Ardiya", name: "Ardiya" },
            { code: "Ardiya Herafiya", name: "Ardiya Herafiya" },
            { code: "Ardiya Industrial Area", name: "Ardiya Industrial Area" },
            { code: "Ashbelya", name: "Ashbelya" },
            { code: "Dhajeej", name: "Dhajeej" },
            { code: "Farwaniya", name: "Farwaniya" },
            { code: "Fordous", name: "Fordous" },
            { code: "Jleeb Al-Shuyoukh", name: "Jleeb Al-Shuyoukh" },
            { code: "Khaitan", name: "Khaitan" },
            { code: "Omariya", name: "Omariya" },
            { code: "Rabiya", name: "Rabiya" },
            { code: "Rai", name: "Rai" },
            { code: "Riggae", name: "Riggae" },
            { code: "Rihab", name: "Rihab" },
            { code: "Sabah Al-Nasser", name: "Sabah Al-Nasser" },
            { code: "Sabaq Al Hajan", name: "Sabaq Al Hajan" },
          ],
        },
        {
          code: "KW3",
          name: " Al Jahra",
          city: [
            { code: "Abdali", name: "Abdali" },
            {
              code: "Al Nahda/East Sulaibikhat",
              name: "Al Nahda/East Sulaibikhat",
            },
            { code: "Amghara", name: "Amghara" },
            { code: "Bar Jahra", name: "Bar Jahra" },
            { code: "Jahra", name: "Jahra" },
            { code: "Jahra Industrial Area", name: "Jahra Industrial Area" },
            { code: "Kabad", name: "Kabad" },
            { code: "Naeem", name: "Naeem" },
            { code: "Nasseem", name: "Nasseem" },
            { code: "Oyoun", name: "Oyoun" },
            { code: "Qasr", name: "Qasr" },
            { code: "Saad Al Abdullah City", name: "Saad Al Abdullah City" },
            { code: "Salmi", name: "Salmi" },
            { code: "Sikrab", name: "Sikrab" },
            { code: "South Doha/Qairawan", name: "South Doha/Qairawan" },
            { code: "Sulaibiya", name: "Sulaibiya" },
            {
              code: "Sulaibiya Agricultural Area",
              name: "Sulaibiya Agricultural Area",
            },
            { code: "Taima", name: "Taima" },
            { code: "Waha", name: "Waha" },
          ],
        },
        {
          code: "KW4",
          name: "Mubarak Al-Kabeer",
          city: [
            { code: "Abu Al Hasaniya", name: "Abu Al Hasaniya" },
            { code: "Abu Futaira", name: "Abu Futaira" },
            { code: "Adan", name: "Adan" },
            { code: "Al Qurain", name: "Al Qurain" },
            { code: "Al-Qusour", name: "Al-Qusour" },
            { code: "Fintas", name: "Fintas" },
            { code: "Funaitas", name: "Funaitas" },
            { code: "Misala", name: "Misala" },
            { code: "Mubarak Al-Kabeer", name: "Mubarak Al-Kabeer" },
            { code: "Sabah Al-Salem", name: "Sabah Al-Salem" },
            { code: "Sabhan", name: "Sabhan" },
            { code: "South Wista", name: "South Wista" },
            { code: "Wista", name: "Wista" },
          ],
        },
        {
          code: "KW5",
          name: "Hawalli",
          city: [
            { code: "Anjafa", name: "Anjafa" },
            { code: "Bayan", name: "Bayan" },
            { code: "Bi'da", name: "Bi'da" },
            { code: "Hawalli", name: "Hawalli" },
            { code: "Hittin", name: "Hittin" },
            { code: "Jabriya", name: "Jabriya" },
            { code: "Maidan Hawalli", name: "Maidan Hawalli" },
            { code: "Mishrif", name: "Mishrif" },
            { code: "Mubarak Al-Jabir", name: "Mubarak Al-Jabir" },
            { code: "Nigra", name: "Nigra" },
            { code: "Rumaithiya", name: "Rumaithiya" },
            { code: "Salam", name: "Salam" },
            { code: "Salmiya", name: "Salmiya" },
            { code: "Salwa", name: "Salwa" },
            { code: "Sha'ab", name: "Sha'ab" },
            { code: "Shuhada", name: "Shuhada" },
            { code: "Siddiq", name: "Siddiq" },
            { code: "South Surra", name: "South Surra" },
            { code: "Zahra", name: "Zahra" },
          ],
        },
        {
          code: "KW6",
          name: "Al Asimah",
          city: [
            { code: "Kuwait City", name: "Kuwait City" },
            { code: "Abdullah as-Salim", name: "Abdullah as-Salim" },
            { code: "Adiliya", name: "Adiliya" },
            { code: "Bneid il-Gar", name: "Bneid il-Gar" },
            { code: "Da'iya", name: "Da'iya" },
            { code: "Dasma", name: "Dasma" },
            { code: "Dasman", name: "Dasman" },
            { code: "Doha", name: "Doha" },
            { code: "Doha Port", name: "Doha Port" },
            { code: "Faiha'", name: "Faiha'" },
            { code: "Failaka", name: "Failaka" },
            { code: "Granada", name: "Granada" },
            { code: "Jaber Al-Ahmad City", name: "Jaber Al-Ahmad City" },
            { code: "Jibla", name: "Jibla" },
            { code: "Kaifan", name: "Kaifan" },
            { code: "Khaldiya", name: "Khaldiya" },
            { code: "Mansariya", name: "Mansariya" },
            { code: "Mirgab", name: "Mirgab" },
            { code: "Nahdha", name: "Nahdha" },
            { code: "Nuzha", name: "Nuzha" },
            { code: "Qadsiya", name: "Qadsiya" },
            { code: "Qurtuba", name: "Qurtuba" },
            { code: "Rawda", name: "Rawda" },
            { code: "Salhiya", name: "Salhiya" },
            { code: "Sawabir", name: "Sawabir" },
            { code: "Shamiya", name: "Shamiya" },
            { code: "Sharq", name: "Sharq" },
            { code: "Shuwaikh", name: "Shuwaikh" },
            {
              code: "Shuwaikh Industrial Area",
              name: "Shuwaikh Industrial Area",
            },
            { code: "Shuwaikh Port", name: "Shuwaikh Port" },
            { code: "Sulaibikhat", name: "Sulaibikhat" },
            { code: "Surra", name: "Surra" },
            { code: "Umm an Namil Island", name: "Umm an Namil Island" },
            { code: "Yarmak", name: "Yarmak" },
            { code: "North West Sulaibikhat", name: "North West Sulaibikhat" },
          ],
        },
      ],
    },
    {
      code: "UG",
      name: "Uganda",
      province: [
        {
          code: "CREG",
          name: "Central Region",
          city: [
            { code: "Buikwe", name: "Buikwe" },
            { code: "Bukomansimbi", name: "Bukomansimbi" },
            { code: "Butambala", name: "Butambala" },
            { code: "Buvuma", name: "Buvuma" },
            { code: "Gomba", name: "Gomba" },
            { code: "Kalangala", name: "Kalangala" },
          ],
        },
        {
          code: "EREG",
          name: "Eastern Region",
          city: [
            { code: "Amuria", name: "Amuria" },
            { code: "Budaka", name: "Budaka" },
            { code: "Bududa", name: "Bududa" },
            { code: "Bugiri", name: "Bugiri" },
            { code: "Bugweri", name: "Bugweri" },
            { code: "Bukedea", name: "Bukedea" },
          ],
        },
      ],
    },
  ],
  vasType: [
    { code: "VAS", name: "VAS", default: true },
    { code: "CUG", name: "CUG" },
    { code: "FNF", name: "FRIENDS AND FAMILY" },
    { code: "CISBundle", name: "CISBundle" },
    { code: "PakaPaka", name: "PakaPaka" },
    { code: "Yange", name: "Yange" },
  ],
  partyType: [
    {
      code: "Individual",
      name: "Individual Customer",
      category: [
        {
          code: "INDV",
          name: "INDIVIDUAL",
          default: true,
          subCategory: [
            { code: "CASB", name: "CORP AND SMALL BUSINESSE" },
            { code: "FORO", name: "FOREIGN ORGANIZATION" },
            { code: "GOVN", name: "GOVERNMENT" },
            { code: "INV", name: "INDIVIDUAL" },
            { code: "MART", name: "MARKET TRANSFER" },
            { code: "PREP", name: "PREPAID" },
            { code: "VIP", name: "VIP" },
          ],
        },
        {
          code: "STAFF",
          name: "STAFF",
          creditLimitIndex: 120,
          subCategory: [
            { code: "GUET", name: "GUESTS" },
            { code: "INTL", name: "INTERNAL LINES" },
            { code: "STFB", name: "BOARD MEMBERS" },
            { code: "STFF", name: "STAFF GROUPS" },
          ],
        },
      ],
    },
    {
      code: "Organization",
      name: "Corporate Registration",
      default: true,
      category: [
        {
          code: "CORP",
          name: "CORPORATE",
          default: true,
          subCategory: [
            { code: "CORA", name: "CORPORATE ACCOUNT", default: true },
            { code: "DIST", name: "DISTRIBUTORS" },
            { code: "SUPP", name: "SUPPLIERS" },
          ],
        },
        {
          code: "LE",
          name: "Large Enterprise",
          subCategory: [
            {
              code: "Domestic",
              name: "CORPORATE ACCOUNT",
              subCategory: [
                {
                  code: "Private Domestic",
                  name: "SUB CORPORATE ACCOUNT",
                  default: true,
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
                {
                  code: "Public Domestic",
                  name: "Public Domestic",
                  default: true,
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
            {
              code: "MNC",
              name: "MNC",
              subCategory: [
                {
                  code: "International MNC",
                  name: "International MNC",
                  default: true,
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
                {
                  code: "Regional MNC",
                  name: "Regional MNC",
                  default: true,
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
          ],
        },
        {
          code: "SME",
          name: "Small & Medium Enterprise",
          subCategory: [
            {
              code: "SOHO",
              name: "DISTRIBUTORS",
              default: true,
              subCategory: [
                {
                  code: "SOHO",
                  name: "SUB DISTRIBUTORS",
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
            {
              code: "Micro",
              name: "Micro",
              default: true,
              subCategory: [
                {
                  code: "Micro",
                  name: "Micro",
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
            {
              code: "Small",
              name: "Small",
              default: true,
              subCategory: [
                {
                  code: "Small",
                  name: "Small",
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
            {
              code: "Medium",
              name: "Medium",
              default: true,
              subCategory: [
                {
                  code: "Medium",
                  name: "Medium",
                  subCategory: [
                    {
                      code: "Administration",
                      name: "Administration",
                      default: true,
                    },
                    { code: "Agriculture", name: "Agriculture" },
                    {
                      code: "Automobile services",
                      name: "Automobile services",
                    },
                    { code: "Financial services", name: "Financial services" },
                    { code: "Construction", name: "Construction" },
                    { code: "Fintech", name: "Fintech" },
                    { code: "Education", name: "Education" },
                    { code: "Utilitiy & Energy", name: "Utilitiy & Energy" },
                    { code: "Fashion", name: "Fashion" },
                    {
                      code: "Hotels, Restaurants & Cafes",
                      name: "Hotels, Restaurants & Cafes",
                    },
                    { code: "Furniture", name: "Furniture" },
                    { code: "Utility & Energy", name: "Utility & Energy" },
                    { code: "Healthcare", name: "Healthcare" },
                    {
                      code: "Industry & Manufacturing",
                      name: "Industry & Manufacturing",
                    },
                    { code: "Insurance services", name: "Insurance services" },
                    {
                      code: "Consultancy services",
                      name: "Consultancy services",
                    },
                    { code: "Real Estate", name: "Real Estate" },
                    { code: "Security services", name: "Security services" },
                    { code: "Transport", name: "Transport" },
                    { code: "Tourism & Travel", name: "Tourism & Travel" },
                    { code: "Food processing", name: "Food processing" },
                    { code: "Other", name: "Other" },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  purpose: [
    {
      code: "POID",
      name: "Proof of Identity",
      description: "Upload your identity proof",
      default: true,
    },
    {
      code: "ageProof",
      name: "Age Proof",
      description: "Upload your age proof",
    },
    {
      code: "addressProof",
      name: "Proof of Address",
      description: "Upload your address proof",
    },
    {
      code: "companyRegistration",
      name: "Company Registration",
      description: "Company Registration",
    },
    {
      code: "purchaseOrder",
      name: "Purchase Order",
      description: "Purchase Order",
    },
    {
      code: "contractForm",
      name: "Contract Form",
      description: "upload your contract form",
    },
    {
      code: "paymentSlip",
      name: "Payment Slip",
      description: "upload your payment slip",
    },
    {
      code: "designDocument",
      name: "Design Document",
      description: "upload your design document",
    },
    {
      code: "licenseDocument",
      name: "License Document",
      description: "upload your license document",
    },
    {
      code: "equipmentSpecificationDetails",
      name: "Equipment Specification Details",
      description: "upload your equipment specification details",
    },
    {
      code: "networkTopologyDiagram",
      name: "Network Topology Diagram",
      description: "upload your network topology diagram",
    },
    {
      code: "NCACertificate",
      name: "NCA Certificate",
      description: "upload your NCA certificate",
    },
    {
      code: "digitalServicesDocument",
      name: "Digital Services Document",
      description: "upload your Digital Services Document",
    },
    {
      code: "troubleTicket",
      name: "Trouble Ticket",
      description: "Trouble Ticket",
    },
    { code: "other", name: "Other", description: "Other" },
    { code: "taxExemptionProof", name: "Tax Excemption Proof" },
    { code: "accountOwnerNID", name: "Account Owner NID" },
  ],
  documentType: [
    { code: "purchaseOrder", name: "Purchase Order" },
    { code: "contractForm", name: "Contract Form" },
    {
      code: "paymentSlip",
      name: "Payment Slip",
      optionalCharacteristics: ["expiryDate"],
    },
    { code: "designDocument", name: "Design Document" },
    { code: "licenseDocument", name: "License Document" },
    {
      code: "equipmentSpecificationDetails",
      name: "Equipment Specification Details",
    },
    { code: "networkTopologyDiagram", name: "Network Topology Diagram" },
    { code: "NCACertificate", name: "NCA Certificate" },
    { code: "digitalServicesDocument", name: "Digital Services Document" },
    {
      code: "customerImage",
      name: "Customer Image",
      optionalCharacteristics: ["expiryDate"],
    },
    { code: "1", name: "COMPANY REGISTRATION" },
    { code: "passport", name: "PASSPORT" },
    {
      code: "nationalId",
      name: "National ID",
      optionalCharacteristics: ["expiryDate"],
    },
    { code: "drivingLicense", name: "Driving License" },
    { code: "4", name: "NIA CARD" },
    { code: "6", name: "NHIS CARD" },
    { code: "CCC", name: "NHIS CARD" },
    { code: "BRN", name: "Buisness Registration Number" },
    { code: "CUST_AGREEMENT_FORM", name: "Customer Agrement Form" },
    {
      code: "PhotoID",
      name: "Photo ID",
      optionalCharacteristics: ["expiryDate"],
    },
  ],
  riskCategory: [
    { code: "HIGH", name: "HIGH RISK CATEGORY" },
    { code: "LOW", name: "LOW RISK CATEGORY" },
    { code: "MED", name: "MEDIUM RISK CATEGORY" },
  ],
  maritalStatus: [
    { code: "S", name: "Single" },
    { code: "M", name: "Married" },
    { code: "D", name: "Divorced" },
  ],
  title: [
    { code: "DR", name: "DR." },
    { code: "MR", name: "MR" },
    { code: "MISS", name: "MISS" },
    { code: "MRS", name: "MRS" },
    { code: "MASTER", name: "MASTER" },
    { code: "OTHERS", name: "OTHERS" },
  ],
  suffix: [
    { code: "SR", name: "SR" },
    { code: "JR", name: "JR" },
  ],
  preferredTime: [
    { code: "9 AM To 1 PM ", name: "9 AM To 1 PM" },
    { code: "1 PM To 8 PM", name: "1 PM To 8 PM" },
  ],
  preferredModeOfCommunication: [
    { code: "1", name: "Post" },
    { code: "2", name: "Email", default: true },
    { code: "3", name: "SMS" },
  ],
  applicationMode: [
    { code: "Call-In", name: "Call-In", default: true },
    { code: "Referral", name: "Referral" },
    { code: "Email", name: "Email" },
    { code: "Dealer", name: "Dealer" },
  ],
  billDispatchMode: [
    { code: "Paper", name: "Post", default: true },
    { code: "Email", name: "Email" },
    { code: "Voice", name: "Voice" },
    { code: "Einvoice", name: "Einvoice" },
  ],
  addressType: [
    {
      code: "Residence",
      name: "Residence",
      addressLevel: "Profile",
      party: { "@type": "Individual" },
      default: true,
    },
    {
      code: "Permanent",
      name: "Permanent",
      addressLevel: "Profile",
      party: { "@type": "Individual" },
    },
    {
      code: "Office",
      name: "Office",
      addressLevel: "Profile",
      party: { "@type": "Organization" },
    },
    { code: "Billing", name: "Billing", addressLevel: "Account" },
    { code: "Service", name: "Service", addressLevel: "Service" },
  ],
  highestQualification: [
    { code: "ASD", name: "Associated Degree" },
    { code: "BHE", name: "Bachelor" },
    { code: "DEG", name: "Degree" },
    { code: "DIP", name: "Diploma" },
    { code: "GD", name: "Graduate" },
    { code: "HSC", name: "Some High School" },
    { code: "MAS", name: "Master" },
    { code: "PHD", name: "PhD" },
    { code: "UED", name: "Uneducated" },
  ],
  nationality: [
    { code: "GHANAIAN", name: "Ghanaian", default: true },
    { code: "Iranian", name: "Iranian" },
    { code: "Foriegner", name: "Foriegner" },
    { code: "FINNISH", name: "FINNISH" },
    { code: "BRITISH", name: "BRITISH" },
  ],
  gender: [
    { code: "M", name: "Male" },
    { code: "F", name: "Female" },
    { code: "TG", name: "Transgender" },
  ],
  currency: [
    { code: "GHS", name: "Ghanaian Cedi", symbol: "‎GH₵", default: true },
    { code: "USD", name: "USD Dollar" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "‎KD" },
  ],
  cardType: [
    { code: "mastercard", name: "mastercard", default: true },
    { code: "american-express", name: "american-express" },
    { code: "diners-club", name: "diners-club" },
    { code: "discover", name: "discover" },
    { code: "jcb", name: "jcb" },
    { code: "unionpay", name: "unionpay" },
    { code: "maestro", name: "maestro" },
    { code: "mir", name: "mir" },
    { code: "elo", name: "elo" },
    { code: "hiper", name: "hiper" },
    { code: "hipercard", name: "hipercard" },
  ],
  topPlans: [
    {
      name: "Postpaid SIM",
      key: "productSpecification.LoB=Mobile&businessType=Postpaid",
    },
    {
      name: "Prepaid SIM",
      key: "productSpecification.LoB=Mobile&businessType=Prepaid",
    },
    {
      name: "Broadband",
      key: "productSpecification.LoB=Broadband&businessType=Postpaid",
    },
    {
      name: "IPTV",
      key: "productSpecification.LoB=IPTV&businessType=Postpaid",
    },
  ],
  serviceType: [
    {
      code: "Mobile",
      name: "Mobile",
      technologyType: [
        { code: "GSM", name: "GSM" },
        { code: "TDD-LTE", name: "TDD-LTE" },
      ],
      subServiceType: [
        { code: "Voice", name: "Voice", default: true },
        { code: "Data", name: "Data" },
      ],
    },
    {
      code: "FixedLine",
      name: "Fixed Line",
      technologyType: [
        { code: "Fiber", name: "Fiber" },
        { code: "Copper", name: "Copper" },
        { code: "GSM", name: "GSM" },
      ],
      subServiceType: [
        {
          code: "Telephone",
          name: "Line",
          default: true,
          technologyType: [
            { code: "Fiber", name: "Fiber" },
            { code: "Copper", name: "Copper" },
          ],
        },
        {
          code: "Broadband",
          name: "Broadband",
          technologyType: [
            { code: "Fiber", name: "Fiber" },
            { code: "Copper", name: "Copper" },
          ],
        },
        {
          code: "Businessboost",
          name: "Business Boost",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "FlyBox",
          name: "Fly Box",
          technologyType: [{ code: "GSM", name: "GSM", default: true }],
        },
        {
          code: "GIP",
          name: "Global IP",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "SIP",
          name: "SIP",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "MPLS",
          name: "MPLS",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "IPLC",
          name: "IPLC",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "WAN",
          name: "WAN / WAN VPN",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "EVLL",
          name: "EVLL",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "VSAT",
          name: "VSAT",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "TVHTL",
          name: "TV for hotel",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "OFF",
          name: "Office 365",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "COLC",
          name: "Colocation",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "FLCOM",
          name: "Flexible Computing",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "WEB",
          name: "Web Hosting",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "SFBB",
          name: "Super Fast Broadband",
          technologyType: [{ code: "Fiber", name: "Fiber" }],
        },
        {
          code: "ADSL",
          name: "ADSL",
          technologyType: [{ code: "Copper", name: "Copper" }],
        },
        {
          code: "MYTIRS",
          name: "MyT IRS",
          technologyType: [{ code: "Copper", name: "Copper" }],
        },
      ],
    },
    {
      code: "IPTV",
      name: "IPTV",
      default: "N",
      technologyType: [{ code: "IPTV", name: "IPTV" }],
      subServiceType: [{ code: "", name: "", default: true }],
    },
    {
      code: "Broadband",
      name: "Broadband",
      default: "N",
      technologyType: [
        { code: "Fiber", name: "Fiber" },
        { code: "Copper", name: "Copper" },
      ],
      subServiceType: [{ code: "", name: "", default: true }],
    },
    {
      code: "M2M",
      name: "M2M",
      technologyType: [{ code: "M2M", name: "M2M" }],
    },
    {
      code: "DigitalServices",
      name: "Digital Service",
      default: true,
      technologyType: [
        { code: "USSD", name: "USSD" },
        { code: "SMS", name: "SMS" },
        { code: "BusinessMessenger", name: "Business Messenger" },
        { code: "BusinessManager", name: "Business Manager" },
      ],
      subServiceType: [{ code: "", name: "", default: true }],
    },
    {
      code: "ICTServices",
      name: "ICT Services",
      technologyType: [
        { code: "LeasedLine", name: "Leased Line" },
        { code: "DedicatedInternet", name: "Dedicated Internet" },
        { code: "DataCentre", name: "Data Centre/Colocation" },
        { code: "GlobalMPLS", name: "Global MPLS" },
        { code: "BulkLease", name: "Bulk Lease" },
        { code: "EnterpriseWiFi", name: "Enterprise Wi-Fi" },
        { code: "NonGSM", name: "Non Gsm" },
      ],
    },
  ],
  businessType: [
    { code: "Prepaid", name: "Prepaid" },
    { code: "Postpaid", name: "Postpaid", default: true },
    { code: "Hybrid", name: "Hybrid" },
  ],
  channel: [{ code: "DCLM", name: "DCLM" }],
  customerRequest: [
    {
      code: "BillingAccountUpdateRequest",
      name: "Telecom Master Nomination Request",
      requestLevel: "account",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "CustomerInformationUpdateRequest",
      name: "Telecom Master Nomination Request",
      requestLevel: "profile",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "LinkProductUserRequest",
      name: "Link ProductUser",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "DeLinkProductUserRequest",
      name: "DeLink ProductUser",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "GroupDataShareManageConsumerRequest",
      name: "Group Data Share",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "WalletStateChangeRequest",
      name: "Wallet Blocking",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "WalletPinResetRequest",
      name: "Wallet Pin Rest",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "PaymentReversalRequest",
      name: "Payment Reversal",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    { code: "customerRequest", name: "EnrollmentQueryRequest", visible: false },
    {
      code: "CustomerInformationUpdateRequest",
      name: "Customer Update",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    { code: "BillingAccountUpdateRequest", name: "Billing Account Update" },
    {
      code: "PromiseToPayRequest",
      name: "Promise To Pay",
      requestLevel: "account",
      maximumLimit: 3,
      maximumPeriod: 6,
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "PaymentAgainstInvoiceRequest",
      name: "Pay Bill",
      requestLevel: "account",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "HoldUnholdDunningRequest",
      name: "Dunning Hold/UnHold",
      requestLevel: "account",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "DuplicateBillRequest",
      name: "Duplicate Bill",
      requestLevel: "account",
      visible: true,
      reason: [
        { code: "01", name: "Lost Original Bill" },
        { code: "02", name: "Need For Personal Reference" },
      ],
    },
    {
      code: "InterimBillRequest",
      name: "Interim Bill",
      visible: true,
      reason: [
        { code: "01", name: "Lost Original Bill" },
        { code: "02", name: "Need For Personal Reference" },
      ],
    },
    {
      code: "PortInRequest",
      name: "Port In",
      requestLevel: "account",
      visible: true,
      quickAction: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "CorporatePortInRequest",
      name: "Corporate Port In",
      requestLevel: "account",
      visible: true,
      quickAction: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "RegistrationRequest",
      name: "Retail Registration",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "CorporateRegistrationRequest",
      name: "Corporate Registration",
      visible: true,
      quickAction: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "AddPlanProductRequest",
      name: "Add Service",
      requestLevel: "account",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ModifyPlanProductRequest",
      name: "Modify Plan Product Request",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "SuspendProductRequest",
      name: "Suspension",
      visible: true,
      quickAction: true,
      bulkAction: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "RevokeSuspendProductRequest",
      name: "Revoke Suspend",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "RevokeSoftSuspendProductRequest",
      name: "Revoke Soft Suspend",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "ReverseSuspendProductRequest",
      name: "Reverse Suspend",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "ReverseSoftSuspendProductRequest",
      name: "Reverse Soft Suspend",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "ReverseTerminateProductRequest",
      name: "Reverse Termination",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "SoftSuspendProductRequest",
      name: "Soft Suspension",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Out of Station" },
      ],
    },
    {
      code: "SoftRevokeSuspendProductRequest",
      name: "Soft Revoke Suspend",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "TerminatePlanProductRequest",
      name: "Termination",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "SimChangeRequest",
      name: "SIM Change",
      visible: true,
      quickAction: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "Damaged SIM" },
      ],
    },
    { code: "PushGprsRequest", name: "Push GPRS Setting" },
    { code: "PinPukRequest", name: "Query PIN/PUK" },
    { code: "LoyaltyOnBoardMemberRequest", name: "Loyaty OnBoard Request " },
    {
      code: "ChangeOfServiceIdRequest",
      name: "Change of Service ID",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ChangeLanguageRequest",
      name: "Change of Language",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ResetPasswordRequest",
      name: "Reset password",
      visible: true,
      reason: [{ code: "01", name: "Forgot Password" }],
    },
    {
      code: "ChangeCreditLimitRequest",
      name: "Credit Limit Modification",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ChangePlanProductRequest",
      name: "Change of Plan",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "PostToPreRequest",
      name: "Postpaid To Prepaid",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "PreToPostRequest",
      name: "Prepaid To Postpaid",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    { code: "TroubleTicketRequest", name: "Trouble Ticket", visible: true },
    {
      code: "AddVasProductRequest",
      name: "Add VAS",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "TerminateVASProductRequest",
      name: "Terminate VAS",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "TransferOfOwnershipRequest",
      name: "Transfer Of Ownership",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "RechargeRequest",
      name: "Recharge",
      visible: true,
      quickAction: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "BarUnbarRefillRequest",
      name: "Unbar Refill",
      visible: true,
      quickAction: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "BarUnbarRequest",
      name: "Bar Unbar",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ServiceClassChangeRequest",
      name: "Service Class Change",
      visible: true,
      reason: [
        { code: "01", name: "Customer Request" },
        { code: "02", name: "MSISDN Not Valid" },
      ],
    },
    {
      code: "RelocateProductRequest",
      name: "Relocate Request",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "EquipmentChangeRequest",
      name: "Equipment Change Request",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ModifyOrderRequest",
      name: "Modify Order Request",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "AddWalletBalance",
      name: "Add Wallet Balance",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "BillingAdjustmentRequest",
      name: "Billing Adjustment",
      visible: true,
      requestLevel: "account",
      reason: [{ code: "01", name: "Customer Request" }],
    },
    {
      code: "ModifyPriceRequest",
      name: "Modify Price",
      visible: true,
      reason: [{ code: "01", name: "Customer Request" }],
    },
  ],
  relationship: [
    { name: "Father", code: "01" },
    { name: "Mother", code: "02" },
  ],
  relationManager: [{ name: "Relation Manager List", code: "ROOT/dclmRELMgr" }],
  accountManager: [
    { name: "Account Manager List", code: "ROOT/dclmACMgr", role: "dclmACMgr" },
  ],
  creditController: [
    { name: "Credit Controller List", code: "ROOT/dclmCRCtrl" },
  ],
  projectManager: [{ name: "Project Manager List", code: "ROOT/dclmPRMgr" }],
  billingRegion: [
    { code: "1", name: "Region1" },
    { code: "2", name: "Region2" },
  ],
  incomeRange: [
    { code: "1", name: "Less than 5000" },
    { code: "2", name: "5000 to 15000" },
    { code: "3", name: "15001 to 20000" },
    { code: "4", name: "20001 to 30000" },
    { code: "5", name: "30001 to 40000" },
    { code: "6", name: "Above 40001" },
  ],
  companyType: [
    { code: "1", name: "PUBLIC", default: "Y" },
    { code: "2", name: "PRIVATE" },
    { code: "3", name: "LTD" },
    { code: "4", name: "GUARANTEED" },
    { code: "5", name: "NON PRIVATE SHARE" },
    { code: "6", name: "SHARED" },
    { code: "7", name: "RELATIVE" },
    { code: "8", name: "COOPERATIVE" },
    { code: "9", name: "GOVERRNMENTAL" },
    { code: "10", name: "MINISTRY" },
    { code: "11", name: "EMBASSY" },
    { code: "12", name: "MOSQUE" },
    { code: "13", name: "SCHOOL" },
    { code: "14", name: "NGO" },
  ],
  keyAccountGroup: [{ code: "KGA01", name: "SOHO" }],
  industry: [
    { code: "IT01", name: "Electronics" },
    { code: "IT02", name: "Energy" },
    { code: "IT03", name: "Engineering" },
    { code: "IT04", name: "Entertainment" },
    { code: "IT05", name: "Facilities Mgt" },
    { code: "IT06", name: "Finance" },
    { code: "IT07", name: "FMCG" },
    { code: "IT08", name: "Foreign Mission" },
    { code: "IT09", name: "Government" },
    { code: "IT10", name: "Healthcare" },
    { code: "IT11", name: "Hospitality" },
    { code: "IT12", name: "ICT" },
    { code: "IT13", name: "NGO" },
    { code: "IT14", name: "Agriculture" },
    { code: "IT15", name: "Agrochemical" },
    { code: "IT16", name: "Automobile" },
    { code: "IT17", name: "Banking" },
    { code: "IT18", name: "Brewery" },
    { code: "IT19", name: "Church Organisation" },
    { code: "IT20", name: "Communications" },
    { code: "IT21", name: "Construction" },
    { code: "IT22", name: "Consulting" },
    { code: "IT23", name: "Education" },
    { code: "IT24", name: "Insurance" },
    { code: "IT25", name: "Manufacturing" },
    { code: "IT26", name: "Media" },
    { code: "IT27", name: "Mining" },
    { code: "IT28", name: "NGO" },
    { code: "IT29", name: "Oil & Gas" },
    { code: "IT30", name: "Other" },
    { code: "IT31", name: "Parastatal" },
    { code: "IT32", name: "Plantation" },
    { code: "IT33", name: "Processing" },
    { code: "IT34", name: "Professional Services" },
    { code: "IT35", name: "Shipping & Logistics" },
    { code: "IT36", name: "Technology" },
    { code: "IT37", name: "Individual" },
    { code: "OTH", name: "OTHERS" },
  ],
  employees: [
    { code: "1", name: "Less than 100" },
    { code: "2", name: "101 to 500" },
    { code: "3", name: "501 to 1000" },
  ],
  xDirLevel: [
    { code: "1", name: "Level 1" },
    { code: "2", name: "Level 2" },
    { code: "3", name: "Level 3" },
    { code: "4", name: "Level 4" },
    { code: "5", name: "Level 5" },
    { code: "6", name: "Level 6" },
    { code: "7", name: "Level 7" },
    { code: "8", name: "Level 8" },
    { code: "9", name: "Level 9" },
    { code: "10", name: "Level 10" },
  ],
  transactionTypes: [
    { code: "Invoice", name: "Invoice" },
    { code: "DebitNote", name: "Debit Note" },
    { code: "Cheque Bounce", name: "Cheque Bounce" },
    { code: "Balance Transfers Debit", name: "Balance Transfers Debit" },
    { code: "CreditNote", name: "Credit Note" },
    { code: "Receipt", name: "Receipts" },
    { code: "Receipt Reversal Debit", name: "Receipt Reversal Debit" },
    {
      code: "Debit of Refunded Transactions",
      name: "Debit of Refunded Transactions",
    },
    { code: "Balance Transfers Credit", name: "Balance Transfers Credit" },
    { code: "Receipt", name: "POS Debit" },
    { code: "Receipt", name: "POS Credit" },
    { code: "Deposit Refund", name: "Deposit Refund" },
    { code: "Excess Payment Debit Note", name: "Excess Payment Debit Note" },
    { code: "WHT", name: "WHT" },
    { code: "Dispute", name: "Dispute" },
  ],
  contractType: [
    { name: "Auto-Renewal", code: "01" },
    { name: "Non-Renewal", code: "02" },
    { name: "Limited", code: "03" },
  ],
  contractPeriod: [
    { name: "12 Months", code: "01" },
    { name: "24 Months", code: "02" },
  ],
  noticePeriod: [
    { name: "1 Month", code: "01" },
    { name: "2 Months", code: "02" },
  ],
  billingStartType: [
    { name: "Contract Signature Date", code: "01" },
    { name: "Service Activation Date", code: "02" },
  ],
  stagedData: [
    { name: "Onboarding", code: "Onboarding" },
    { name: "Customer Acceptance", code: "Customer Acceptance" },
    { name: "Add Service", code: "Add Service" },
  ],
  notificationTemplates: [
    { id: "custom", title: "Custom Message", body: "" },
    {
      id: "welcome",
      title: "Welcome",
      body:
        "Welcome to our network. To use data services please make sure Data Roaming is enabled in your device settings.",
    },
  ],
  documentExpiryPeriod: 10,
  mobileMoneyWalletStates: {
    activeMessage: "MTNU Mobile Money Subscriber",
    blockedMessage: "MTNU Mobile Money Subscriber No Rating",
  },
  promiseDaysPostDueDate: 45,
  paymentReversalDaysPostPaymentReceiptDate: 90,
  totalPromise: 10,
  documentGracePeriod: 10,
};
