const formAPIData = [
  {
    id: 'SV1EZ81IR85',
    href: 'http://https://dclm.cluster1.devtestlab2.tecnotree.com//v1/step/SV1EZ81IR85',
    createdDate: '2021-03-24T11:54:57.753Z',
    modifiedDate: '2021-04-12T05:31:09.164Z',
    formName: 'Partner_Profile',
    formIdentity: 'Partner_Profile',
    stepIdentity: 'PartnerProfileCreation',
    stepType: 'freeStep',
    status: true,
    customStep: false,
    formStepNo: 1,
    workFlowName: 'Potential Partner Info New',
    workFlowId: '1617270248702',
    column: [
      'section1',
      'section20',
      'section33',
      'section64',
      'section47',
      'section35',
      'section9',
      'section46'
    ],
    stepProperties: {
      linkedTo: {},
      stepHistory: []
    },
    sectionlist: {
      section1: {
        sectiontitle: 'Partner Details',
        arr: [
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PARTNER NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'PARTNER_NAME',
            id: 233,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 0,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PARTNER REGISTRATION NUMBER',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'PARTNER_REGISTRATION_NUMBER',
            id: 182,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 1,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'ORGANISATION',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'ORGANISATION',
            id: '1617255689809',
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 2,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: 'Enter Username Without Space',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'USERNAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '^[a-zA-Z0-9]*$',
            min: ' ',
            name: 'USERNAME',
            id: 696,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 3,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'SSO ROLE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'SSO_ROLE',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 391,
            placeholder: 'Please Choose',
            value: '',
            order: 4,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: '',
            isApiData: true,
            workFlowId: '1617098560465',
            workflowName: 'Get SSO Roles'
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'INDUSTRY TYPE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'INDUSTRY_TYPE',
            options: [
              {
                id: 1,
                value: 'Food & Beverage',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Hospitality',
                name: 'option2'
              },
              {
                id: '161726061864436176',
                value: 'Healthcare',
                name: 'option64486322'
              },
              {
                id: '161726062676616817',
                value: 'Sports',
                name: 'option76641862'
              },
              {
                id: '161726063577657896',
                value: 'Entertainment',
                name: 'option77547079'
              },
              {
                id: '161726064421695123',
                value: 'IoT',
                name: 'option21692502'
              }
            ],
            id: 446,
            placeholder: 'Please Choose',
            value: '',
            order: 5,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PARTNER TYPE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'PARTNER_TYPE',
            options: [
              {
                id: 1,
                value: 'Digital Service Partner',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Equipment Partner',
                name: 'option2'
              },
              {
                id: '161726101076474400',
                value: 'Smart Service Location Partners (BOT)',
                name: 'option76465912'
              }
            ],
            id: 971,
            placeholder: 'Please Choose',
            value: '',
            order: 6,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'SUB TYPE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'SUB_TYPE',
            options: [
              {
                id: 1,
                value: 'E commerce Software',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Scandit Customized Solution',
                name: 'option2'
              },
              {
                id: '161726108212059535',
                value: 'Esignature',
                name: 'option12094846'
              },
              {
                id: '1617261081678180',
                value: 'Digital Restaurants',
                name: 'option67870148'
              },
              {
                id: '161726111651389591',
                value: 'Learning Management Solution',
                name: 'option51345981'
              },
              {
                id: '161726111607197306',
                value: 'CPE Partner or vendor',
                name: 'option07141377'
              },
              {
                id: '161726113947731442',
                value: 'Digital Signage Solutions',
                name: 'option47735065'
              },
              {
                id: '161726113892564138',
                value: 'Smart Building Solutions',
                name: 'option92586163'
              },
              {
                id: '161726115822613835',
                value: 'Time Attendance',
                name: 'option22653471'
              },
              {
                id: '161726115792588587',
                value: 'Fleet & Driver Management Systems',
                name: 'option92527042'
              },
              {
                id: '161726117957382782',
                value: 'Thermal Screening Cameras',
                name: 'option5732781'
              },
              {
                id: '161726117924747637',
                value: 'Big Building',
                name: 'option24748413'
              },
              {
                id: '161726120082789639',
                value: 'Malls',
                name: 'option82770945'
              },
              {
                id: '161726120053126416',
                value: 'Airport',
                name: 'option5316977'
              }
            ],
            id: 645,
            placeholder: 'Please Choose',
            value: '',
            order: 7,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Optional Details',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'Optional_Details',
            id: '1618205456674',
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 8,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'SOURCE',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'SOURCE',
            id: '1618205328352',
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 9,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'WEBSITE URL',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'WEBSITE_URL',
            id: '1618205358837',
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 10,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'NUMBER OF EMPLOYEES',
            type: 'dropdown',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'NUMBER_OF_EMPLOYEES',
            options: [
              {
                id: 1,
                value: '1 - 50',
                name: 'option1'
              },
              {
                id: 2,
                value: '50 - 500',
                name: 'option2'
              },
              {
                id: '161726142074528113',
                value: '500 - 1000',
                name: 'option74592916'
              },
              {
                id: '161726142026221342',
                value: '1000 - 5000',
                name: 'option26280997'
              },
              {
                id: '161726143739734151',
                value: '5000 - 10000',
                name: 'option39787987'
              },
              {
                id: '161726144684556163',
                value: '10000 - 15000',
                name: 'option84595889'
              },
              {
                id: '161726145691869024',
                value: '15000+',
                name: 'option91822268'
              }
            ],
            id: 198,
            placeholder: 'Please Choose',
            value: '',
            order: 11,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          }
        ]
      },
      section20: {
        arr: [
          {
            fId: 'multiline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'ADDRESS LINE 1',
            type: 'textarea',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'ADDRESS_LINE_1',
            id: 449,
            placeholder: 'Please Enter ',
            value: '',
            order: 0,
            fieldType: 'Multi Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'CITY',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'CITY',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 976,
            placeholder: 'Please Choose',
            value: '',
            order: 1,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'STATE OF ORIGIN',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'STATE_OF_ORIGIN',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 926,
            placeholder: 'Please Choose',
            value: '',
            order: 2,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'COUNTRY',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'COUNTRY',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 606,
            placeholder: 'Please Choose',
            value: '',
            order: 3,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PO BOX',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'PO_BOX',
            id: 909,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 4,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'LANDMARK',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'LANDMARK',
            id: 929,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 5,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          }
        ],
        sectiontitle: 'Company Address'
      },
      section33: {
        arr: [
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'BILLING NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'BILLING_NAME',
            id: 118,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 0,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'BILL PREFERRED LANGUAGE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'BILL_PREFERRED_LANGUAGE',
            options: [
              {
                id: 1,
                value: 'English',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Kuwaiti',
                name: 'option2'
              }
            ],
            id: 800,
            placeholder: 'Please Choose',
            value: '',
            order: 1,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PERIODICITY',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'PERIODICITY',
            options: [
              {
                id: 1,
                value: 'Monthly',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Quarterly',
                name: 'option2'
              },
              {
                id: '161726161668363790',
                value: 'Yearly',
                name: 'option68315195'
              }
            ],
            id: 469,
            placeholder: 'Please Choose',
            value: '',
            order: 2,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'BILL CURRENCY',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'BILL_CURRENCY',
            options: [
              {
                id: 1,
                value: 'Kuwaiti Dinar',
                name: 'option1'
              },
              {
                id: 2,
                value: 'US Dollar',
                name: 'option2'
              }
            ],
            id: 593,
            placeholder: 'Please Choose',
            value: '',
            order: 3,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'BILL CYCLE',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'BILL_CURRENCY',
            options: [
              {
                id: 1,
                value: '1st-31st',
                name: 'option1'
              },
              {
                id: 2,
                value: '2nd-1st',
                name: 'option2'
              },
              {
                id: '161726169084410860',
                value: '3rd-2nd',
                name: 'option84445392'
              },
              {
                id: '161726168981685713',
                value: '4th-3rd',
                name: 'option81650559'
              }
            ],
            id: 441,
            placeholder: 'Please Choose',
            value: '',
            order: 4,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'BILLING REGION',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'BILLING_REGION',
            options: [
              {
                id: 1,
                value: 'Region 1',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Region 2',
                name: 'option2'
              },
              {
                id: '161726172913676636',
                value: 'Region 3',
                name: 'option13669842'
              },
              {
                id: '161726172865482367',
                value: 'Region 4',
                name: 'option65458599'
              }
            ],
            id: 31,
            placeholder: 'Please Choose',
            value: '',
            order: 5,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'switch',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: '',
            label: 'Tax Exempted',
            type: 'switch',
            required: true,
            errorMsg: '',
            regex: '',
            min: '',
            name: 'Tax_Exempted',
            id: 243,
            placeholder: '',
            value: '',
            order: 6,
            fieldType: 'Switch',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'date',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EXEMPTION TILL',
            type: 'date',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'EXEMPTION_TILL',
            id: '1617261847470',
            placeholder: 'Please Enter ',
            value: '',
            order: 7,
            fieldType: 'Date',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EXEMPTED TAX POLICY',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'EXEMPTED_TAX_POLICY',
            options: [
              {
                id: 1,
                value: 'CST @ 1%',
                name: 'option1'
              },
              {
                id: 2,
                value: 'CST @ 4%',
                name: 'option2'
              },
              {
                id: '161726199194178274',
                value: 'CST @ 8%',
                name: 'option94146788'
              }
            ],
            id: 17,
            placeholder: 'Please Choose',
            value: '',
            order: 8,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          }
        ],
        sectiontitle: 'Billing Details'
      },
      section64: {
        arr: [
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PRIMARY CONTACT NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'PRIMARY_CONTACT_NAME',
            id: 538,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 0,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PRIMARY CONTACT LAST NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'PRIMARY_CONTACT_LAST_NAME',
            id: 855,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 1,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'dropdown',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'DESIGNATION',
            type: 'dropdown',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'DESIGNATION',
            options: [
              {
                id: 1,
                value: 'Admin',
                name: 'option1'
              },
              {
                id: 2,
                value: 'Sales',
                name: 'option2'
              },
              {
                id: '161726203475787441',
                value: 'Finance',
                name: 'option7564368'
              }
            ],
            id: 72,
            placeholder: 'Please Choose',
            value: '',
            order: 2,
            fieldType: 'DropDown',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'MOBILE NUMBER',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'MOBILE_NUMBER',
            id: 249,
            placeholder: 'Please Enter ',
            value: 0,
            order: 6,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EMAIL ID',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'EMAIL_ID',
            id: 778,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 7,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'WHATSAPP',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'WHATSAPP',
            id: 171,
            placeholder: 'Please Enter ',
            value: 0,
            order: 8,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PHONE NUMBER',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'PHONE_NUMBER',
            id: 669,
            placeholder: 'Please Enter ',
            value: 0,
            order: 9,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EXTENION NUMBER',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'EXTENION_NUMBER',
            id: 412,
            placeholder: 'Please Enter ',
            value: 0,
            order: 10,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'DEPARTMENT',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'DEPARTMENT',
            id: 92,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 11,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'CONTACT MEDIUM',
            type: 'text',
            required: false,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'CONTACT_MEDIUM',
            id: 675,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 12,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Email',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Email',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 453,
            placeholder: 'Please Choose ',
            value: '',
            order: 13,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'SMS',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'SMS',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 65,
            placeholder: 'Please Choose ',
            value: '',
            order: 14,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Watsapp',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Watsapp',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 845,
            placeholder: 'Please Choose ',
            value: '',
            order: 15,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Telegram',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Telegram',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 174,
            placeholder: 'Please Choose ',
            value: '',
            order: 16,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'hidden',
            instructions: '',
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: '',
            label: 'LOGIN TYPE',
            type: 'hidden',
            required: false,
            errorMsg: '',
            regex: '',
            min: '',
            name: 'LOGIN_TYPE',
            id: 978,
            placeholder: '',
            value: '',
            order: 17,
            fieldType: 'Hidden',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: '',
            defaultValue: 'HierarchicalUser'
          }
        ],
        sectiontitle: 'Primary Contact Details'
      },
      section47: {
        arr: [
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'ADDITIONAL LAST NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'ADDITIONAL_LAST_NAME',
            id: 225,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 0,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'ADDITIONAL NAME',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'ADDITIONAL_NAME',
            id: 961,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 1,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'ADDITIONAL DESIGNATION',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'ADDITIONAL_DESIGNATION',
            id: 875,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 2,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'emailid',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EMAIL(Additional)',
            type: 'email',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'EMAIL(Additional)',
            id: 383,
            placeholder: 'Please Enter ',
            value: '',
            order: 3,
            fieldType: 'Email ID',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'WHATSAPP(Additional)',
            type: 'number',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'WHATSAPP(Additional)',
            id: 148,
            placeholder: 'Please Enter ',
            value: 0,
            order: 4,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'PHONE NUMBER(Additional)',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'PHONE_NUMBER(Additional)',
            id: 856,
            placeholder: 'Please Enter ',
            value: 0,
            order: 5,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'EXTENTION NUMBER(Additional)',
            type: 'number',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'EXTENTION_NUMBER(Additional)',
            id: 2,
            placeholder: 'Please Enter ',
            value: 0,
            order: 6,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'DEPARTMENT(Additional)',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'DEPARTMENT(Additional)',
            id: 386,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 7,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Contact Medium(Additional)',
            type: 'text',
            required: true,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'Contact_Medium(Additional)',
            id: 929,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 8,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'SMS(Additional)',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'SMS(Additional)',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 231,
            placeholder: 'Please Choose ',
            value: '',
            order: 9,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Email(Additional)',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Email(Additional)',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 209,
            placeholder: 'Please Choose ',
            value: '',
            order: 10,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Whatsapp(Additional)',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Whatsapp(Additional)',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 664,
            placeholder: 'Please Choose ',
            value: '',
            order: 11,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'checkbox',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Telegram(Additional)',
            type: 'checkbox',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Telegram(Additional)',
            options: [
              {
                id: 1,
                value: '',
                name: 'option1'
              },
              {
                id: 2,
                value: '',
                name: 'option2'
              }
            ],
            id: 389,
            placeholder: 'Please Choose ',
            value: '',
            order: 12,
            fieldType: 'CheckBox',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          }
        ],
        sectiontitle: 'Additional Contact'
      },
      section35: {
        arr: [
          {
            fId: 'button',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: '',
            label: 'Add',
            type: 'Button',
            required: false,
            errorMsg: '',
            regex: '',
            min: '',
            name: 'Add',
            id: 497,
            placeholder: '',
            value: '',
            order: 0,
            fieldType: 'Button',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: '',
            style: 'Outlined',
            apiHeader: [
              {
                id: '073-b178-e2ba2952d619',
                bodyKey: '',
                bodyValue: ''
              }
            ],
            buttonType: 'proceed'
          },
          {
            fId: 'hidden',
            instructions: '',
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: '',
            label: 'ROLE',
            type: 'hidden',
            required: 'false',
            errorMsg: '',
            regex: '',
            min: '',
            name: 'ROLE',
            id: 394,
            placeholder: '',
            value: '',
            order: 1,
            fieldType: 'Hidden',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: '',
            defaultValue: 'RO1041'
          }
        ],
        sectiontitle: 'Add Another Contact'
      },
      section9: {
        arr: [
          {
            fId: 'singleline',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'NAME',
            type: 'text',
            required: false,
            errorMsg: 'Please Enter MID',
            regex: '',
            min: ' ',
            name: 'NAME',
            id: 195,
            placeholder: 'Please Enter Registred MID',
            value: '',
            order: 0,
            fieldType: 'Single Line',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'emailid',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'MANAGER EMAIL',
            type: 'email',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'MANAGER_EMAIL',
            id: 738,
            placeholder: 'Please Enter ',
            value: '',
            order: 1,
            fieldType: 'Email ID',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          },
          {
            fId: 'phone',
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'MOBILE NUMBER',
            type: 'number',
            required: false,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'MOBILE_NUMBER',
            id: 804,
            placeholder: 'Please Enter ',
            value: 0,
            order: 3,
            fieldType: 'Phone',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: ''
          }
        ],
        sectiontitle: 'Partner Relationship Manager'
      },
      section46: {
        arr: [
          {
            fId: 'fileupload',
            filetype: [
              {
                checked: 'false',
                id: '1',
                label: '.jpeg'
              },
              {
                checked: 'false',
                id: '2',
                label: '.pdf'
              },
              {
                checked: 'false',
                id: '3',
                label: '.csv'
              },
              {
                checked: 'false',
                id: '4',
                label: '.doc'
              },
              {
                checked: 'false',
                id: '5',
                label: '.docx'
              },
              {
                checked: 'false',
                id: '6',
                label: '.png'
              }
            ],
            instructions: '',
            visible: true,
            max: '',
            autoFill: '',
            icon: 'fa fa-pencil-square-o',
            tooltip: 'This field',
            label: 'Company Registration',
            type: 'upload',
            resolution: '',
            required: true,
            errorMsg: 'Please Enter',
            regex: '',
            min: '',
            name: 'Company_Registration',
            id: 952,
            placeholder: 'Please Enter ',
            value: '',
            order: 0,
            fieldType: 'File Upload',
            linkedTo: false,
            formIdentity: '',
            stepIdentity: '',
            kyctype: [
              {
                checked: 'false',
                id: '1',
                label: '.jpeg'
              },
              {
                checked: 'false',
                id: '2',
                label: '.pdf'
              },
              {
                checked: 'false',
                id: '3',
                label: '.csv'
              },
              {
                checked: 'false',
                id: '4',
                label: '.doc'
              },
              {
                checked: 'false',
                id: '5',
                label: '.docx'
              },
              {
                checked: 'false',
                id: '6',
                label: '.png'
              }
            ]
          }
        ],
        sectiontitle: 'UPLOAD DOCUMENTS'
      }
    },
    stepFooter: [
      {
        id: 46,
        label: 'Save and Exit',
        type: 'Button',
        name: 'Save_and_Exit46',
        value: '',
        required: 'false',
        min: '',
        order: 0,
        max: '',
        fieldType: 'Button',
        regex: '',
        icon: 'fa fa-pencil-square-o',
        Api: 'https://dclm.cluster1.devtestlab2.tecnotree.com/digital-partnership-management/digital-partnership-management-back-end-dynamic-forms/v1/submit',
        buttonType: 'save',
        style: 'Outlined'
      }
    ],
    stepTitle: '',
    stepCategory: '',
    path: 'http://https://dclm.cluster1.devtestlab2.tecnotree.com//v1/step',
    '@baseType': 'Step',
    '@schemaLocation':
      'http://https://dclm.cluster1.devtestlab2.tecnotree.com//v1/step/schema'
  }
];
export default formAPIData;
